---
## hosts: all
- hosts: pwd
  tasks:
     - name: Update apt-cache 
       apk: update_cache=yes
       when: ansible_facts['distribution'] == "Alpine"
             
     - name: Update apt-cache 
       apt: update_cache=yes
       when: ansible_facts['distribution'] == "Debian"
     
# ansible_facts['distribution'] values
# Alpine
# Altlinux
# Amazon
# Archlinux
# ClearLinux
# Coreos
# Debian
# Gentoo
# Mandriva
# NA
# OpenWrt
# OracleLinux
# RedHat
# Slackware
# SMGL
# SUSE
# VMwareESX
 